### ISSUE TITLE
Early feedback

### ISSUE THREAD

**Issue by ro0gr** [yratanov/ember-page-object-asserts#1]
@yratanov I like the direction here, we should definitely build assertions API based on the actual page object instance shape. 

However, when looking at `assert.po(page.link).href('google.com');` I'm unsure. Maybe it's just a matter of a taste, but it doesn't feel super clear to me what it really does, until I look at source code.

There are basically 2 kinds of props I know:

 1. those who responds with boolean, `isHighlighted`, `hasSomething`, `readonly`,... I think this is perfectly fine to use the same assertion name for those, like we do for `.isHighlighted()`, cause they all can be tested with "yes" or "no" with strict equality check.
 2. Non-boolean values. For example `string` as we do have for `href`. Strict equality check can be not sufficient for that. We may also want to check for a substring occurence. I think for such cases it can be useful to have extra asserts:

```js
assert.po(page.link).href.is('google.com');
assert.po(page.link).href.includes('.com');
```

_Note, here I don't invoke `href`, but instead use it as a container for assertions. this way it becomes a bit more readable and straightforward (imo)._

**Comment by yratanov** [comment]
@ro0gr thank you for your feedback! 
Yeah, I agree, having it like this will give us more flexibility.
